[2025-01-20T12:25:29.662+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T12:25:29.698+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cryptobot_workflow.fastapi manual__2025-01-20T12:24:28.357176+00:00 [queued]>
[2025-01-20T12:25:29.708+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cryptobot_workflow.fastapi manual__2025-01-20T12:24:28.357176+00:00 [queued]>
[2025-01-20T12:25:29.709+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-20T12:25:29.720+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): fastapi> on 2025-01-20 12:24:28.357176+00:00
[2025-01-20T12:25:29.728+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=143) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-20T12:25:29.729+0000] {standard_task_runner.py:72} INFO - Started process 144 to run task
[2025-01-20T12:25:29.731+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cryptobot_workflow', 'fastapi', 'manual__2025-01-20T12:24:28.357176+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/cryptobot_dag.py', '--cfg-path', '/tmp/tmpfijze2t8']
[2025-01-20T12:25:29.732+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask fastapi
[2025-01-20T12:25:29.789+0000] {task_command.py:467} INFO - Running <TaskInstance: cryptobot_workflow.fastapi manual__2025-01-20T12:24:28.357176+00:00 [running]> on host fd5a16ffbc98
[2025-01-20T12:25:29.890+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cryptobot_workflow' AIRFLOW_CTX_TASK_ID='fastapi' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T12:24:28.357176+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-20T12:24:28.357176+00:00'
[2025-01-20T12:25:29.892+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-20T12:25:29.892+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-20T12:25:29.893+0000] {logging_mixin.py:190} INFO - Current task name:fastapi state:running start_date:2025-01-20 12:25:29.698907+00:00
[2025-01-20T12:25:29.893+0000] {logging_mixin.py:190} INFO - Dag name:cryptobot_workflow and current dag run status:running
[2025-01-20T12:25:29.893+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T12:25:29.894+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-20T12:25:29.895+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/src/fastapi-mongo.py']
[2025-01-20T12:25:29.914+0000] {subprocess.py:99} INFO - Output:
[2025-01-20T12:25:36.316+0000] {subprocess.py:106} INFO - INFO:     Will watch for changes in these directories: ['/tmp/***tmpjeinmzdd']
[2025-01-20T12:25:36.321+0000] {subprocess.py:106} INFO - INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
[2025-01-20T12:25:36.322+0000] {subprocess.py:106} INFO - INFO:     Started reloader process [146] using StatReload
[2025-01-20T12:25:44.993+0000] {subprocess.py:106} INFO - INFO:     Started server process [162]
[2025-01-20T12:25:44.997+0000] {subprocess.py:106} INFO - INFO:     Waiting for application startup.
[2025-01-20T12:26:15.399+0000] {subprocess.py:106} INFO - ERROR:    Traceback (most recent call last):
[2025-01-20T12:26:15.404+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
[2025-01-20T12:26:15.405+0000] {subprocess.py:106} INFO -     async with self.lifespan_context(app) as maybe_state:
[2025-01-20T12:26:15.406+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.408+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
[2025-01-20T12:26:15.409+0000] {subprocess.py:106} INFO -     return await anext(self.gen)
[2025-01-20T12:26:15.410+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.411+0000] {subprocess.py:106} INFO -   File "/opt/***/src/fastapi-mongo.py", line 74, in lifespan
[2025-01-20T12:26:15.412+0000] {subprocess.py:106} INFO -     await create_collection(app.state.db, "market_data")
[2025-01-20T12:26:15.412+0000] {subprocess.py:106} INFO -   File "/opt/***/src/fastapi-mongo.py", line 46, in create_collection
[2025-01-20T12:26:15.413+0000] {subprocess.py:106} INFO -     if collection_name not in await db.list_collection_names():
[2025-01-20T12:26:15.414+0000] {subprocess.py:106} INFO -                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.415+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 59, in run
[2025-01-20T12:26:15.416+0000] {subprocess.py:106} INFO -     result = self.fn(*self.args, **self.kwargs)
[2025-01-20T12:26:15.417+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.418+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/database.py", line 1206, in list_collection_names
[2025-01-20T12:26:15.419+0000] {subprocess.py:106} INFO -     return self._list_collection_names(session, filter, comment, **kwargs)
[2025-01-20T12:26:15.420+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.420+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/database.py", line 1171, in _list_collection_names
[2025-01-20T12:26:15.421+0000] {subprocess.py:106} INFO -     result["name"] for result in self._list_collections_helper(session=session, **kwargs)
[2025-01-20T12:26:15.421+0000] {subprocess.py:106} INFO -                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.422+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/database.py", line 1118, in _list_collections_helper
[2025-01-20T12:26:15.422+0000] {subprocess.py:106} INFO -     return self._client._retryable_read(
[2025-01-20T12:26:15.423+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.423+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 1863, in _retryable_read
[2025-01-20T12:26:15.423+0000] {subprocess.py:106} INFO -     return self._retry_internal(
[2025-01-20T12:26:15.424+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.424+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/_csot.py", line 120, in csot_wrapper
[2025-01-20T12:26:15.424+0000] {subprocess.py:106} INFO -     return func(self, *args, **kwargs)
[2025-01-20T12:26:15.424+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.425+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 1830, in _retry_internal
[2025-01-20T12:26:15.425+0000] {subprocess.py:106} INFO -     ).run()
[2025-01-20T12:26:15.425+0000] {subprocess.py:106} INFO -       ^^^^^
[2025-01-20T12:26:15.425+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 2554, in run
[2025-01-20T12:26:15.426+0000] {subprocess.py:106} INFO -     return self._read() if self._is_read else self._write()
[2025-01-20T12:26:15.426+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^
[2025-01-20T12:26:15.426+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 2689, in _read
[2025-01-20T12:26:15.427+0000] {subprocess.py:106} INFO -     self._server = self._get_server()
[2025-01-20T12:26:15.427+0000] {subprocess.py:106} INFO -                    ^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.427+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 2645, in _get_server
[2025-01-20T12:26:15.427+0000] {subprocess.py:106} INFO -     return self._client._select_server(
[2025-01-20T12:26:15.428+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.428+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 1649, in _select_server
[2025-01-20T12:26:15.428+0000] {subprocess.py:106} INFO -     server = topology.select_server(
[2025-01-20T12:26:15.428+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.428+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/topology.py", line 398, in select_server
[2025-01-20T12:26:15.429+0000] {subprocess.py:106} INFO -     server = self._select_server(
[2025-01-20T12:26:15.429+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.429+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/topology.py", line 376, in _select_server
[2025-01-20T12:26:15.429+0000] {subprocess.py:106} INFO -     servers = self.select_servers(
[2025-01-20T12:26:15.429+0000] {subprocess.py:106} INFO -               ^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.430+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/topology.py", line 283, in select_servers
[2025-01-20T12:26:15.430+0000] {subprocess.py:106} INFO -     server_descriptions = self._select_servers_loop(
[2025-01-20T12:26:15.430+0000] {subprocess.py:106} INFO -                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-20T12:26:15.430+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/synchronous/topology.py", line 333, in _select_servers_loop
[2025-01-20T12:26:15.430+0000] {subprocess.py:106} INFO -     raise ServerSelectionTimeoutError(
[2025-01-20T12:26:15.431+0000] {subprocess.py:106} INFO - pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 678e40c8948726b991be812e, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2025-01-20T12:26:15.431+0000] {subprocess.py:106} INFO - 
[2025-01-20T12:26:15.431+0000] {subprocess.py:106} INFO - ERROR:    Application startup failed. Exiting.
[2025-01-20T12:26:15.431+0000] {subprocess.py:106} INFO - Connecting to MongoDB...
[2025-01-20T12:26:15.431+0000] {subprocess.py:106} INFO - Error during startup: 127.0.0.1:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 678e40c8948726b991be812e, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
